Adding a -long test parameters to run long-running tests
ldsec/lattigo pull request #75
Opened 2020-11-06 14:32 UTC by ChristianMct

As in tite.

2020-11-06 14:56 UTC, Pro7ech requested changes

2020-11-06 14:56 UTC, Pro7ech commented on dckks/dckks_test.go
> +		defaultParams = ckks.DefaultParams[ckks.PN12QP109 : ckks.PN12QP109+2] // the short test runs for ring degree N=2^12, 2^13, 2^14, 2^15
This will go up to 2^{13} only

2020-11-06 14:56 UTC, Pro7ech commented on dckks/dckks_test.go
> +	var defaultParams = ckks.DefaultParams[ckks.PN12QP109 : ckks.PN12QP109+3] // the default test runs for ring degree N=2^12, 2^13, 2^14
Set to same as the other schemes

2020-11-06 15:34 UTC, ChristianMct commented on dckks/dckks_test.go
> +	var defaultParams = ckks.DefaultParams[ckks.PN12QP109 : ckks.PN12QP109+3] // the default test runs for ring degree N=2^12, 2^13, 2^14
fixed

2020-11-06 15:37 UTC, ChristianMct commented on dckks/dckks_test.go
> +		defaultParams = ckks.DefaultParams[ckks.PN12QP109 : ckks.PN12QP109+2] // the short test runs for ring degree N=2^12, 2^13, 2^14, 2^15
Good catch, fixed

2020-11-07 14:18 UTC, Pro7ech approved these changes

2020-11-07 15:21 UTC, merged